# Numpy : Numpy adalah library untuk numerical computing

In [ ]:
import numpy as np

Array dengan rank 1 dan panjang 3

In [ ]:
[1,2,3]

[1, 2, 3]

Array dengan rank 2 panjang 3

In [ ]:
[[1,2,3], [4,5,6]]

[[1, 2, 3], [4, 5, 6]]

**ndarray** adalah nama class untuk sebuah numpy Array

In [ ]:
a = np.array ([1, 2, 3])
b = np.array ([(1, 2, 3), (4, 5, 6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


# Properti ndaarray

* ndarray.ndim = Untuk mengetahui jumlah dimensi (Rank) dari sebuah numpy array.
* ndarray.shape = Untuk mengetahui jumlah baris dan kolom pada sebuah numpy array.
* ndarray.size = Untuk mengetahui jumlah elemen dalam sebuah numpy array.
* ndarray.dtype = untuk mengetahui data type dari elemen yang ada di numpy array.
* ndarray.itemsize = untuk mengetahui ukuran elemen (bytes) yang ada di numpy array.
ndarray.data = buffer untuk meyimpan elemen - elemen didalam numpy array.

In [ ]:
a = np.array ([1, 2, 3])
b = np.array ([(1, 2, 3), (4, 5, 6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(3,)
3
int64
8


In [ ]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

2
(2, 3)
6
int64
8


# Create Numpy Array

*  np.zeros : Semua array isinya 0 (Nol)
*  np.ones : Semua array isinya 1 (satu)
*  np.arange : memberikan scope dan panjang step
* np.linspace : memberikan scope dan jumlah elemen yang diinginkan
* np.random.random : memberikan angka acak

In [ ]:
np.zeros ((3, 3)) # membuat sebuah array zero dengan dimensi 3 dan elemen setiap dimensinya 3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(1,2, 0.2) # Membuat sebuah array dengan range angka dari 1 - 2 (maksimal angka 2 ) dengan panjang atau jarak setiap elemen 0.3 point

array([1. , 1.2, 1.4, 1.6, 1.8])

In [ ]:
np.linspace(1, 3, 6) # Membuat sebuah array dengan range angka 1- 3 dengan 6 elemen didalamnya

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [ ]:
np.random.random ((2, 3))

array([[0.49958102, 0.07991998, 0.47419344],
       [0.77192433, 0.57348384, 0.04015259]])

# Shape and Operation

*  reshape : mengubah dimensi / shape dari sebuah numpy array
*  vstack : Stack numppy array secara vertical
*  hstack : stack numpy array scara horizontal
*  vsplit : split numpy array secara vertical
*  hsplit : split numpy array secara horizontal

In [ ]:
a = np.array ([(1, 2, 3), (4, 5, 6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Reshape sebuah array

a = a.reshape (3, -1) # Artinya adalah merubah dimensi array a yang semula 2 baris 3 kolom, menjadi 3 baris dan otomatis kolom diatur sistem (-1) angka -1 juga bisa kita atur sendiri jumlah kolomnya
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# vstack sebuah array

b = np.array ([(7, 8), (9, 10)])
b

array([[ 7,  8],
       [ 9, 10]])

In [ ]:
# Menggabungkan Array a dan b secara vertical
# Harus mempunyai kolom yang sama
a = np.array ([(1, 2), (3, 4), (5, 6)])
b = np.array ([(7, 8), (9, 10)])

print (a)
print (b)

np.vstack ((a, b))



[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# Menggabungkan array secara horizontal
# Harus mempunyai baris/ dimensi yang sama

a = np.array ([(1, 2, 3), (4, 5, 6)])
b = np.array ([(11, 12, 13), (14, 15, 16)])
print(a)
print(b)

np.hstack((a, b))

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]


array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [ ]:
# Vertikal Split sebuah array
# adalah membagi array yang diiris lewat baris

a = np.array([(1, 2, 3, 11, 12, 13), (4, 5, 6, 14, 15, 16)]) # Array 2 baris
print(a)

np.split(a, 2) # Array di split menjadi 2, kalau di split jadi 3 akan error, karena jumlah baris atau dimensinya cuma 2

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


[array([[ 1,  2,  3, 11, 12, 13]]), array([[ 4,  5,  6, 14, 15, 16]])]

In [ ]:
# Horizontal Split sebuah array
# adalah membagi array yng diiris lewat kolom

a = np.array([(1, 2, 3, 11, 12, 13), (4, 5, 6, 14, 15, 16)])
print(a)

np.hsplit(a, 3) # Array di split menjadi 3, kalau di split jadi 5 akan error, karena jumlah kolom atau elemmnya cuma 6

print(' ')

np.hsplit(a, (1, 3)) # Split setelah kolom 1 dan 3

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]
 


[array([[1],
        [4]]),
 array([[2, 3],
        [5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]])]

# INDEXING

In [ ]:
data = np.arange(100, 200) # Membuat sebuah data dengan array 1 dimensi yang isi nya 100 - 200 (200 tidak termasuk)
print(data)
print ('')

index_lima = np.arange(0, 100, 5) # membuat sebuah index dengan menggunkana array yang nantinya muncul kelipatan 5 dimulai dari 0

print(index_lima)
print ('')

print(data[index_lima]) # memunculkan semua data array dengan index kelipatan lima

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

[100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]


In [ ]:
data2D = data.reshape (10, -1)

print(data2D) # Memunculkan semua elemen array
print('')

print(data2D[2]) # ini akan memunculkan baris ke 2 dari emelen array
print('')

print(data2D[2, 1]) # ini akan memunculkan array yang ada pada baris 2 kolom 1
print('')

print(data2D[-1, -1]) # ini akan memunculkan array yang ada pada baris terakhir dan kolom terakhir
print('')

print(data2D[:, 3]) # Artinya adalah mengakses semua data pada kolom 3
print('')

print(data2D[1:4, 3:5]) # artinya adalah memunculkan data dari baris 1 - 3 (4 tidak termasuk) dan kolom 3-4 (5 tidak termasuk)


[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]

[120 121 122 123 124 125 126 127 128 129]

121

199

[103 113 123 133 143 153 163 173 183 193]

[[113 114]
 [123 124]
 [133 134]]
